name: Deploy Backend to Render
on:
  push:
    branches:
      - main
    paths:
      - 'love-confession-api/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"serviceId": "'$RENDER_SERVICE_ID'"}' \
          https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
